language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

# faster builds on new travis setup not using sudo
sudo: false

services:
  - mysql

install:
  - '[[ -z "$CI_USER_TOKEN" ]] || composer config github-oauth.github.com ${CI_USER_TOKEN};'
  - travis_retry composer self-update && composer --version
  - composer require symfony/event-dispatcher:v3.4
  - composer update --prefer-dist --no-interaction
  - git clone -q --depth=1 -b codeception-2.2 https://github.com/codeception/codeception-lumen-sample.git framework-tests
  - git --git-dir framework-tests/.git log -n 1
  - travis_retry composer update -d framework-tests --no-dev --prefer-dist --no-interaction
  - php ./vendor/bin/codecept build -c framework-tests

before_script:
  - cp framework-tests/.env.testing framework-tests/.env
  - touch framework-tests/storage/testing.sqlite
  - php framework-tests/artisan migrate --database=testing --force
script:
  - php ./vendor/bin/codecept run functional -c framework-tests
