name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [5.6, 7.0, 7.1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: zip, pdo, sqlite
        coverage: none

    - name: Checkout Lumen Sample
      uses: actions/checkout@v2
      with:
        repository: codeception/codeception-lumen-sample
        path: framework-tests
        ref: codeception-2.2

    - name: Install Lumen Sample
      run: |
        composer update -d framework-tests --no-dev --prefer-dist --no-interaction
        cp .env.testing .env
        touch storage/testing.sqlite
        php artisan migrate --database=testing --force
      working-directory: framework-tests

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction --no-suggest

    - name: Run test suite
      run: |
        php vendor/bin/codecept build -c framework-tests
        php vendor/bin/codecept run functional -c framework-tests
