name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql

    strategy:
      matrix:
        php: [5.6, 7.0, 7.1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, php-xml, ext-dom, zip
        coverage: none

    - name: Install Lumen Sample
      run: |
        git clone -q --depth=1 -b codeception-2.2 https://github.com/codeception/codeception-lumen-sample.git framework-tests
        git --git-dir framework-tests/.git log -n 1
        composer update -d framework-tests --no-dev --prefer-dist --no-interaction
        php ./vendor/bin/codecept build -c framework-tests
        cp framework-tests/.env.testing framework-tests/.env
        touch framework-tests/storage/testing.sqlite
        php framework-tests/artisan migrate --database=testing --force

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: php ./vendor/bin/codecept run functional -c framework-tests
