name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql

    strategy:
      matrix:
        php: [5.6, 7.0, 7.1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, php-xml, ext-dom, zip
        coverage: none

    - name: Install Lumen Sample
      run: |
        git clone https://github.com/codeception/codeception-lumen-sample.git framework-tests
        cd framework-tests
        cp .env.testing .env
        composer install
        touch storage/testing.sqlite
        pwd
        ls
        php artisan migrate --database=testing

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: php ./vendor/bin/codecept run functional -c framework-tests
